spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rupe
    username: alfredo
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration